- name: Wazuh High Severity Alert Check
  hosts: 192.168.10.187
  become: yes
  vars:
    wazuh_logs_path: "/var/ossec/logs/alerts/alerts.log"
    alert_level_threshold: 10
    gmail_username: "nikkem100@gmail.com"
    gmail_password: "dan10042002"
    notification_email: "luulinhdan2002@gmail.com"

  tasks:
    - name: Check for high severity alerts
      shell: "grep -c 'level\":{{ alert_level_threshold }}' {{ wazuh_logs_path }}"      register: high_severity_count
      changed_when: false

    - name: Send email notification if high severity alerts found
      mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ gmail_username }}"
        password: "{{ gmail_password }}"
        to: "{{ notification_email }}"
        subject: "Wazuh High Severity Alerts Detected"
        body: "{{ high_severity_count.stdout }} high severity alerts detected in the last 24 hours. Please investigate immediately."
      when: high_severity_count.stdout|int > 0

    - name: Log alert check
      ansible.builtin.lineinfile:
        path: /var/log/wazuh_alert_checks.log
        line: "{{ ansible_date_time.iso8601 }} - Checked for high severity alerts. Found: {{ high_severity_count.stdout }}"
        create: yes
