---
- name: Thu thập cảnh báo Wazuh mức độ cao và gửi về AWX
  hosts: 192.168.10.187
  become: yes
  vars:
    alert_level: 9
    wazuh_alerts_path: "/var/ossec/logs/alerts/alerts.json"
    local_output_file: "/tmp/high_level_alerts.json"
    awx_server: "your_awx_server_ip"
    awx_user: "your_awx_user"
    awx_alerts_dir: "/var/lib/awx/projects/wazuh_alerts"
    alert_time_range: "24h"

  tasks:
    - name: Kiểm tra trạng thái Wazuh manager
      command: /var/ossec/bin/wazuh-control status
      register: wazuh_status
      ignore_errors: yes

    - name: Hiển thị trạng thái Wazuh
      debug:
        var: wazuh_status.stdout_lines

    - name: Khởi động lại Wazuh manager nếu không hoạt động
      command: /var/ossec/bin/wazuh-control restart
      when: wazuh_status.rc != 0 or "'wazuh-manager is running' not in wazuh_status.stdout"
      register: restart_result

    - name: Hiển thị kết quả khởi động lại
      debug:
        var: restart_result.stdout_lines
      when: restart_result is changed

    - name: Lọc cảnh báo mức độ cao
      shell: |
        jq -c 'select(.rule.level >= {{ alert_level }} and .timestamp >= (now - {{ alert_time_range | to_json }}))' {{ wazuh_alerts_path }} > {{ local_output_file }}
      register: filtered_alerts

    - name: Kiểm tra kết quả lọc cảnh báo
      stat:
        path: "{{ local_output_file }}"
      register: filtered_file

    - name: Gửi file cảnh báo đến AWX qua SCP
      command: scp -o StrictHostKeyChecking=no {{ local_output_file }} {{ awx_user }}@{{ awx_server }}:{{ awx_alerts_dir }}/high_level_alerts_{{ ansible_date_time.iso8601 }}.json
      when: filtered_file.stat.exists
      register: scp_result

    - name: Xóa file tạm
      file:
        path: "{{ local_output_file }}"
        state: absent
      when: filtered_file.stat.exists

    - name: Ghi log kết quả trên AWX
      shell: |
        ssh -o StrictHostKeyChecking=no {{ awx_user }}@{{ awx_server }} "echo '{{ ansible_date_time.iso8601 }} - Đã nhận {{ filtered_file.stat.size | default(0) }} byte dữ liệu cảnh báo' >> {{ awx_alerts_dir }}/alerts_transfer.log"
      when: scp_result is success
      ignore_errors: yes

    - name: Thông báo kết quả
      debug:
        msg: "Quá trình thu thập và gửi cảnh báo đã hoàn tất. Kiểm tra log tại {{ awx_alerts_dir }}/alerts_transfer.log trên AWX server"
