---
- name: Thu thập và gửi cảnh báo Wazuh mức độ cao về AWX
  hosts: 192.168.10.187
  become: yes
  vars:
    alert_level: 9
    wazuh_alerts_path: "/var/ossec/logs/alerts/alerts.json"
    output_file: "/tmp/high_level_alerts.json"
    awx_server: "192.168.10.181"
    awx_user: "admin"
    awx_alerts_dir: "/var/lib/awx/incoming_alerts"
    alert_time_range: "48h"

  tasks:
    - name: Kiểm tra kết nối SSH đến AWX
      ping:
      delegate_to: "{{ awx_server }}"

    - name: Kiểm tra file cảnh báo Wazuh
      stat:
        path: "{{ wazuh_alerts_path }}"
      register: alert_file

    - name: Dừng playbook nếu không tìm thấy file cảnh báo
      fail:
        msg: "Không tìm thấy file cảnh báo Wazuh tại {{ wazuh_alerts_path }}"
      when: not alert_file.stat.exists

    - name: Lọc cảnh báo mức độ cao trong khoảng thời gian cụ thể
      shell: |
        jq -c 'select(.rule.level >= {{ alert_level }} and .timestamp >= (now - {{ alert_time_range | to_json }}))' {{ wazuh_alerts_path }} > {{ output_file }}
      register: filtered_alerts

    - name: Kiểm tra kết quả lọc cảnh báo
      stat:
        path: "{{ output_file }}"
      register: filtered_file

    - name: Tạo thư mục đích trên AWX
      file:
        path: "{{ awx_alerts_dir }}"
        state: directory
        mode: '0755'
      delegate_to: "{{ awx_server }}"

    - name: Gửi file cảnh báo đến AWX
      block:
        - copy:
            src: "{{ output_file }}"
            dest: "{{ awx_alerts_dir }}/high_level_alerts_{{ ansible_date_time.iso8601 }}.json"
            mode: '0644'
          delegate_to: "{{ awx_server }}"
          register: copy_result
      rescue:
        - name: Xử lý lỗi gửi file
          debug:
            msg: "Lỗi khi gửi file: {{ ansible_failed_result.msg }}"
          failed_when: true

    - name: Xóa file tạm
      file:
        path: "{{ output_file }}"
        state: absent
      when: filtered_file.stat.exists

    - name: Ghi log kết quả
      lineinfile:
        path: "/var/log/wazuh_alerts_transfer.log"
        line: "{{ ansible_date_time.iso8601 }} - Đã chuyển {{ filtered_file.stat.size | default(0) }} byte dữ liệu cảnh báo"
        create: yes

    - name: Thông báo kết quả
      debug:
        msg: "Quá trình chuyển cảnh báo đã hoàn tất. Kiểm tra log tại /var/log/wazuh_alerts_transfer.log"
