---
- name: Xử lý và lưu trữ cảnh báo Wazuh mức độ cao
  hosts: wazuh_server
  become: yes
  vars:
    alert_level_threshold: 12
    wazuh_alerts_file: "/var/ossec/logs/alerts/alerts.json"
    awx_storage_path: "/var/lib/awx/projects/wazuh_alerts"
    retention_days: 30

  tasks:
    - name: Đọc file cảnh báo Wazuh
      shell: "tail -n 1000 {{ wazuh_alerts_file }} | jq -c 'select(.rule.level >= {{ alert_level_threshold }})'"
      register: high_level_alerts

    - name: Xử lý cảnh báo
      debug:
        msg: "Cảnh báo mức độ cao: {{ item.rule.description }} - Level: {{ item.rule.level }}"
      loop: "{{ high_level_alerts.stdout_lines | map('from_json') | list }}"

    - name: Tạo thư mục lưu trữ cảnh báo trên AWX
      delegate_to: localhost
      file:
        path: "{{ awx_storage_path }}"
        state: directory
        mode: '0755'

    - name: Lưu cảnh báo vào file trên AWX
      delegate_to: localhost
      copy:
        content: "{{ item | to_nice_json }}"
        dest: "{{ awx_storage_path }}/high_alerts_{{ ansible_date_time.date }}.json"
        mode: '0644'
      loop: "{{ high_level_alerts.stdout_lines | map('from_json') | list }}"

    - name: Xóa file cảnh báo cũ
      delegate_to: localhost
      find:
        paths: "{{ awx_storage_path }}"
        patterns: "high_alerts_*.json"
        age: "{{ retention_days }}d"
      register: old_files

    - name: Xóa các file cũ
      delegate_to: localhost
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_files.files }}"

  - name: Gửi thông báo qua email (tùy chọn)
  community.general.mail:
    host: smtp.gmail.com
    port: 587
    username: "nhatdanluu@gmail.com"
    password: "dan10042002"
    to: "luulinhdan2002@gmail.com"
    subject: "Cảnh báo Wazuh mức độ cao"
    body: "Có {{ high_level_alerts.stdout_lines | length }} cảnh báo mức độ cao. Vui lòng kiểm tra file log để biết thêm chi tiết."
  when: high_level_alerts.stdout_lines | length > 0

    - name: Ghi log hoạt động
      delegate_to: localhost
      lineinfile:
        path: "{{ awx_storage_path }}/alert_processing.log"
        line: "{{ ansible_date_time.iso8601 }} - Processed {{ high_level_alerts.stdout_lines | length }} high-level alerts"
        create: yes
