---
- name: Thu thập cảnh báo Wazuh mức độ cao từ AWX sử dụng SSH
  hosts: localhost
  connection: local
  become: no
  vars:
    alert_level: 9
    wazuh_server: "192.168.10.187"
    wazuh_user: "wazuh"
    wazuh_alerts_path: "/var/ossec/logs/alerts/alerts.json"
    local_output_file: "/tmp/high_level_alerts.json"
    awx_alerts_dir: "/var/lib/awx/projects/wazuh_alerts"
    alert_time_range: "48h"

  tasks:
    - name: Kiểm tra kết nối SSH đến Wazuh server
      ansible.builtin.command:
        cmd: ssh -o BatchMode=yes -o ConnectTimeout=5 {{ wazuh_user }}@{{ wazuh_server }} echo OK
      register: ssh_result
      ignore_errors: true

    - name: Dừng playbook nếu không thể kết nối SSH
      ansible.builtin.fail:
        msg: "Không thể kết nối SSH đến Wazuh server {{ wazuh_server }}"
      when: ssh_result.rc != 0

    - name: Kiểm tra file cảnh báo Wazuh từ xa
      ansible.builtin.stat:
        path: "{{ wazuh_alerts_path }}"
      delegate_to: "{{ wazuh_server }}"
      register: alert_file

    - name: Dừng playbook nếu không tìm thấy file cảnh báo
      ansible.builtin.fail:
        msg: "Không tìm thấy file cảnh báo Wazuh tại {{ wazuh_alerts_path }} trên server {{ wazuh_server }}"
      when: not alert_file.stat.exists

    - name: Lọc và truyền cảnh báo mức độ cao trong khoảng thời gian cụ thể
      ansible.builtin.shell: |
        ssh {{ wazuh_user }}@{{ wazuh_server }} "jq -c 'select(.rule.level >= {{ alert_level }} and .timestamp >= (now - {{ alert_time_range | to_json }}))' {{ wazuh_alerts_path }}" > {{ local_output_file }}
      register: filtered_alerts

    - name: Kiểm tra kết quả lọc cảnh báo
      ansible.builtin.stat:
        path: "{{ local_output_file }}"
      register: filtered_file

    - name: Tạo thư mục đích trên AWX
      ansible.builtin.file:
        path: "{{ awx_alerts_dir }}"
        state: directory
        mode: '0755'

    - name: Di chuyển file cảnh báo đến thư mục đích
      ansible.builtin.copy:
        src: "{{ local_output_file }}"
        dest: "{{ awx_alerts_dir }}/high_level_alerts_{{ ansible_date_time.iso8601 }}.json"
        mode: '0644'
      when: filtered_file.stat.exists
      register: copy_result

    - name: Xóa file tạm
      ansible.builtin.file:
        path: "{{ local_output_file }}"
        state: absent
      when: filtered_file.stat.exists

    - name: Ghi log kết quả
      ansible.builtin.lineinfile:
        path: "{{ awx_alerts_dir }}/alerts_transfer.log"
        line: "{{ ansible_date_time.iso8601 }} - Đã chuyển {{ filtered_file.stat.size | default(0) }} byte dữ liệu cảnh báo từ {{ wazuh_server }}"
        create: yes

    - name: Thông báo kết quả
      ansible.builtin.debug:
        msg: "Quá trình thu thập cảnh báo đã hoàn tất. Kiểm tra log tại {{ awx_alerts_dir }}/alerts_transfer.log"
